name: Agregar un curso
description: Sugerir un curso nuevo con material libre para el catálogo
title: "[Curso]: "
body:
- type: textarea
  attributes:
    label: Código
    description: El código del curso
    placeholder: ej. CC3002
  validations:
    required: true
- type: textarea
  attributes:
    label: Nombre
    description: El nombre del curso como aparece en Ucampus
    placeholder: ej. Metodologías de Diseño y Programación
  validations:
    required: true
- type: textarea
  attributes:
    label: Apunte
    description: El enlace al apunte
    placeholder: Documentación online, libros gratis, colabs, etc.
    value: N/A
  validations:
    required: false
- type: textarea
  attributes:
    label: Videos
    description: El enlace a los videos
    placeholder: Playlists, páginas con videos, etc.
    value: N/A
  validations:
    required: false
- type: textarea
  attributes:
    label: Otros recursos
    description: Enlaces a otros recursos
    placeholder: Wikis, repositorios, calendarios, etc.
    value: N/A
  validations:
    required: false
